"""B2: export 80 and 130 mm STLs for the new catalog pieces; record them in catalog/exports.json.

Run:  uv run python scripts/b2_export_stls.py              # all new, printable pieces
      uv run python scripts/b2_export_stls.py -p r2-triakis-tetrahedron

STLs go to ``out/stls/``, which is not committed; print from there. Their hashes, sizes and mesh
facts go to ``catalog/exports.json`` (generated; commit it), together with the code commit they
were built from. Baseline pieces are not exported here: their STLs are the original files, hashed
in ``catalog/pieces.yaml`` (decision 0006).
"""

import argparse
import json

from polyhedral_functions import catalog, meshes
from polyhedral_functions.catalog import EXPORTS_FILE, SIZES_MM
from polyhedral_functions.manifests import REPO_ROOT, git_state, relative


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-p", "--piece", action="append", help="only this piece (repeatable)")
    args = ap.parse_args()

    pieces = [p for p in catalog.load() if p.origin == "new" and not p.digital_only]
    if args.piece:
        pieces = [p for p in pieces if p.id in args.piece]
    record = json.loads(EXPORTS_FILE.read_text(encoding="utf-8")) if EXPORTS_FILE.exists() else {}
    record.setdefault("pieces", {})
    code = git_state()
    out = REPO_ROOT / "out" / "stls"
    for piece in pieces:
        sizes = meshes.export_stl(piece, SIZES_MM, out)
        _, display = meshes.relief_generator(piece)
        record["pieces"][piece.id] = {
            "display": display,
            "resolution": piece.resolution or meshes.DEFAULT_RESOLUTION,
            "code": {"commit": code["commit"], "dirty": code["dirty"]},
            "sizes": sizes,
        }
        print(
            f"{piece.id}: "
            + ", ".join(
                f"{s} mm {v['volume_cm3']} cm3 waist {v['waist_mm']} mm"
                + ("" if v["watertight"] else " NOT WATERTIGHT")
                for s, v in sizes.items()
            )
        )
    record["note"] = (
        "Generated by scripts/b2_export_stls.py. STL files live in out/stls/ (not committed)."
    )
    record["pieces"] = dict(sorted(record["pieces"].items()))
    with EXPORTS_FILE.open("w", encoding="utf-8", newline="\n") as fh:
        json.dump(record, fh, indent=1)
        fh.write("\n")
    print(f"wrote {relative(EXPORTS_FILE)}; STLs in {relative(out)}")


if __name__ == "__main__":
    main()
