"""B2: export whole and cut STLs (80 and 130 mm) for catalog pieces; record them in exports.json.

Run:  uv run python scripts/b2_export_stls.py              # every printable piece
      uv run python scripts/b2_export_stls.py -p r2-triakis-tetrahedron

STLs go to ``out/stls/``, which is not committed; print from there. Their hashes, sizes and mesh
facts go to ``catalog/exports.json`` (generated; commit it), together with the code commit they
were built from.

- **Baseline pieces** are regenerated as well and checked against the hashes in
  ``catalog/pieces.yaml``. This repo reproduces them byte for byte.
- **Pieces with an owner-approved cut plane** also get cut halves in print pose (decision 0007),
  and hanging-ornament halves with a thread hole through one spike (decision 0008).
"""

import argparse
import json

from polyhedral_functions import catalog, meshes
from polyhedral_functions.catalog import EXPORTS_FILE, SIZES_MM
from polyhedral_functions.manifests import REPO_ROOT, git_state, relative


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-p", "--piece", action="append", help="only this piece (repeatable)")
    args = ap.parse_args()

    pieces = [p for p in catalog.load() if not p.digital_only]
    if args.piece:
        pieces = [p for p in pieces if p.id in args.piece]
    record = json.loads(EXPORTS_FILE.read_text(encoding="utf-8")) if EXPORTS_FILE.exists() else {}
    record.setdefault("pieces", {})
    code = git_state()
    out = REPO_ROOT / "out" / "stls"
    for piece in pieces:
        sizes = meshes.export_stl(piece, SIZES_MM, out)
        _, display = meshes.relief_generator(piece)
        entry = {
            "display": display,
            "code": {"commit": code["commit"], "dirty": code["dirty"]},
            "sizes": sizes,
        }
        notes = [
            f"{s} mm waist {v['waist_mm']} mm" + ("" if v["watertight"] else " NOT WATERTIGHT")
            for s, v in sizes.items()
        ]
        if piece.origin == "baseline":
            entry["reproduces_catalog_stl"] = all(
                sizes[str(s)]["sha256"] == piece.stl["files"][s]["sha256"] for s in SIZES_MM
            )
            notes.append(
                "reproduces catalog STLs"
                if entry["reproduces_catalog_stl"]
                else "DOES NOT reproduce catalog STLs"
            )
        else:
            entry["resolution"] = piece.resolution or meshes.DEFAULT_RESOLUTION
        if piece.cut_approved():
            entry["cuts"] = meshes.export_cuts(piece, SIZES_MM, out)
            notes.append(f"cut halves {entry['cuts'][str(SIZES_MM[0])]['halves']}")
            entry["ornament"] = meshes.export_ornament(piece, SIZES_MM, out)
            holes = [entry["ornament"][str(s)]["hole"] for s in SIZES_MM]
            notes.append(
                "ornament hole "
                + ", ".join(
                    f"{s} mm: {h['distance_from_tip_mm']} mm in"
                    for s, h in zip(SIZES_MM, holes, strict=True)
                )
            )
        record["pieces"][piece.id] = entry
        print(f"{piece.id}: " + "; ".join(notes))
    record["note"] = (
        "Generated by scripts/b2_export_stls.py. STL files live in out/stls/ (not committed)."
    )
    record["pieces"] = dict(sorted(record["pieces"].items()))
    with EXPORTS_FILE.open("w", encoding="utf-8", newline="\n") as fh:
        json.dump(record, fh, indent=1)
        fh.write("\n")
    print(f"wrote {relative(EXPORTS_FILE)}; STLs in {relative(out)}")


if __name__ == "__main__":
    main()
